#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorD,          light,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{

 	resetMotorEncoder(light);
 	while(getMotorEncoder(light) < 179)
 	{
 		motor(light) = 25;
	}
  motor(light) = 0;
 	wait1Msec(1000);
	}
}
