#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorD,          light,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int clapcounter = 0;
	while( true)
 {
		while(SensorValue(sound) < 50)
		{

		}
	  while(SensorValue(sound) > 50)
	  {
	  	clapcounter ++;
	  	while(SensorValue(sound) > 50)
	  	{
	  	}
	  }
	  for(int i = 0; i < 10000; i++)
	  {
	  	displayBigTextLine(6, "clapnum %d", clapcounter);
	  }
 }
}
