#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorD,          light,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void flipSwitch()
{
	resetMotorEncoder(light);
	while(getMotorEncoder(light) < 179)
	{
		motor(light) = 25;
	}
	motor(light) = 0;
}
//waiting for first clap
int waitForClap(int clapCounter)
{
	while(SensorValue(sound) < 50)
	{

	}
	if(SensorValue(sound) > 50)
	{
		clapCounter ++;
		while(SensorValue(sound) > 50)
		{

		}
	}
	return clapCounter;
}
//uses for second clap;
int waitForDoubleClap(int clapCounter)
{
	clapCounter = waitForClap(clapCounter);



	resetTimer(timer1);
	while(getTimerValue(timer1) < 1000)
	{
		if(SensorValue(sound) < 100)
		{
			clapCounter ++;
			while(getTimerValue(timer1) < 1001)
			{
				//does nothing
			}
	  }

	}

		return clapCounter;
}
task main()
{

	while( true)
	{
		int clapNum = 0;
		clapNum = waitForDoubleClap(clapNum);
		if(clapNum >= 2)
		{
			flipSwitch();
		}
	}


}
