#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorB,          light,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int clapCount = 0;

	while (true)
	{
		displayTextLine(4, "Sound %d", SensorValue(sound));

		if(SensorValue(sound) >= 50)
		{
			clapCount = clapCount + 1;
			if(clapCount >= 2)
			{
				clapCount = 1;
			}
		}

		if(clapCount == 1 && SensorValue(sound) <= 40)
		{
			clapCount = clapCount + 1;
		}

		if(clapCount == 2)
		{
			motor(light) = 30;
			wait1Msec(300);
			clapCount = 0;
		}

	}

}
