#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorD,          light,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void flipSwitch()
{
	resetMotorEncoder(light);
	while(getMotorEncoder(light) < 179)
	{
		motor(light) = 25;
	}
	motor(light) = 0;
}
int waitForClap(int clapCounter)
{
	while(SensorValue(sound) < 50)
	{
	}
	if(SensorValue(sound) > 50)
	{
		clapCounter ++;
		while(SensorValue(sound) > 50)
		{
		}
	}
	return clapCounter;
}
task main()
{
	int clapNum = 0;
	while( true)
	{
	waitForClap(clapNum);
	flipSwitch();
 }


}
