#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorD,          light,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		waitFor(sensorValue(sound) >= 50)
		{
			if(sensorValue(sound) >= 50)
			{
				getTimerValue;
			}
			if(sensorValue(sound) >= 50 && getTimerValue(time1) < 700)
			{
				motor(light) = 25;
				resetTimerValue(time1);
			}
		}
	}
}
